version: 2.1

jobs:
  linux-build:
    parameters:
      git_install:
        type: string
      configure:
        type: string
      docker_image:
        type: string
      deps_script:
        type: string
    environment:
      ZEEK_CI_CONFIGURE_FLAGS: << parameters.configure >>
      ZEEK_CI_CPUS: 4
      ZEEK_CI_BTEST_JOBS: 2
      ZEEK_CI_BTEST_RETRIES: 2
      ZEEK_CI_RUNNER_OS: linux
      ZEEK_TEST_ULIMIT_OPEN_FILES: 256
      ZEEK_CI_SKIP_EXTERNAL_BTESTS: 1
    docker:
      - image: << parameters.docker_image >>
    steps:
      - run:
          name: Install git
          command: << parameters.git_install >>
      - checkout
      - run:
          name: Install Dependencies
          command: << parameters.deps_script >>
      - run:
          name: Update submodules
          command: git submodule update --recursive --init
      - restore_cache:
          keys:
            - ccache-{{ .Branch }}-{{ .Revision }}
            - ccache-{{ .Branch }}-
            - ccache-
      - run:
          name: Setup ccache
          command: |
            mkdir -p ~/.ccache
            ccache --set-config=max_size=2G
            ccache --set-config=compression=true
            ccache --zero-stats
            ccache --show-stats
      - run:
          name: Build
          command: ci/build.sh
          environment:
      - run:
          name: Show ccache statistics
          command: ccache --show-stats
      - save_cache:
          key: ccache-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.ccache
      - run:
          name: Test
          command: ci/test.sh
      - store_test_results:
          path: btest-results

workflows:
  build-and-test:
    jobs:
      - linux-build:
          name: ubuntu-24.04
          git_install: apt update && apt install -y git
          configure: --build-type=release --disable-broker-tests --prefix=$CIRRUS_WORKING_DIR/install --ccache --enable-werror
          deps_script: ci/ubuntu-24.04/install_dependencies.sh
          docker_image: ubuntu:24.04
      - linux-build:
          name: fedora-43
          git_install: dnf -y install git
          configure: --build-type=release --disable-broker-tests --prefix=$CIRRUS_WORKING_DIR/install --ccache --enable-werror
          deps_script: ci/fedora-43/install_dependencies.sh
          docker_image: fedora:43
